# Generated by Django 5.2.10 on 2026-02-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0002_alter_datasettype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerodataimport',
            name='processed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
