# Generated by Django 5.2.10 on 2026-02-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0003_xerodataimport_processed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xerodataimport',
            name='processed_data',
        ),
    ]
