# Generated by Django 5.2.10 on 2026-02-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_remove_xerodataimport_dataset_type_and_more'),
        ('xero', '0004_remove_xerodataimport_processed_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='xerodataimport',
            name='processed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xerodataimport',
            name='report_id',
            field=models.CharField(blank=True, help_text='Unique identifier linking to parent FinancialReport', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, help_text='Unique identifier for this financial report batch', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_month', models.CharField(blank=True, help_text='Financial report month/period', max_length=20)),
                ('total_rows_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_reports', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='tenant.legalentity')),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='xerodataimport',
            name='financial_report',
            field=models.ForeignKey(blank=True, help_text='Parent financial report this import belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to='xero.financialreport'),
        ),
        migrations.AddIndex(
            model_name='xerodataimport',
            index=models.Index(fields=['report_id'], name='xero_xeroda_report__2abb43_idx'),
        ),
        migrations.AddIndex(
            model_name='xerodataimport',
            index=models.Index(fields=['financial_report'], name='xero_xeroda_financi_7cf040_idx'),
        ),
    ]
