# Generated by Django 5.2.10 on 2026-02-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0005_xerodataimport_processed_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerodataimport',
            name='tenant_name',
            field=models.CharField(blank=True, help_text='Name of the tenant/legal entity at time of import', max_length=255),
        ),
    ]
