# Generated by Django 5.2.10 on 2026-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0006_xerodataimport_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerodataimport',
            name='database_write_status',
            field=models.JSONField(blank=True, default=dict, help_text='Track if database write succeeded/failed with details'),
        ),
        migrations.AddField(
            model_name='xerodataimport',
            name='transformation_status',
            field=models.JSONField(blank=True, default=dict, help_text='Track if report transformation succeeded/failed with details'),
        ),
    ]
