# Generated by Django 5.2.11 on 2026-02-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_logo_alter_tenant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
