# Generated by Django 5.2.10 on 2026-02-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_legalentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('invoices', 'Invoices'), ('bills', 'Bills'), ('contacts', 'Contacts'), ('accounts', 'Chart of Accounts'), ('journal_entries', 'Journal Entries')], max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly display name', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dataset Type',
                'verbose_name_plural': 'Dataset Types',
            },
        ),
        migrations.CreateModel(
            name='XeroDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xero_imports/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('rows_processed', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_imports', to=settings.AUTH_USER_MODEL)),
                ('dataset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.datasettype')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='tenant.legalentity')),
            ],
            options={
                'verbose_name': 'Xero Data Import',
                'verbose_name_plural': 'Xero Data Imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
